### ISSUE TITLE
发现了上传文件的 icon，但是缺少文件下载的 icon

### ISSUE THREAD

**Issue by JhinDeng** [teambition/TB-Icons#8]

**Comment by guan-wy** [comment]
@JhinDeng 

我猜你用的是这个 `upload-file` 小图标吧，目前的确没有下载的小图标。

如果可以的话，你可以先用其他的上下箭头图标代替使用。

<img width="791" alt="2018-06-07 16 36 18" src="https://user-images.githubusercontent.com/12364061/41088026-f2d8c5fe-6a70-11e8-9a39-f83eeb915019.png">

**Comment by guan-wy** [comment]
哦好的，那我去跟设计师建议一下，有时间帮忙新增一个吧，加好了我通知你。

**Comment by guan-wy** [comment]
Added in 89d8978f9d8c59bfc5dcadb2718e2d8c98366952
v0.2.83 has been published

<img width="252" alt="2018-06-14 15 04 42" src="https://user-images.githubusercontent.com/12364061/41396880-e77adaac-6fe4-11e8-86e7-16cda2b56c97.png">
